/*
 * To change this license header, choose License Headers in Project Properties.
 * To    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getElementAt(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.AddQualificationControl;
import businessLogic.AddRoomControl;
import entity.Musician;
import businessLogic.CreateSessionControl;
import businessLogic.CreateStudioControl;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import entity.Room;
import entity.SoundMan;
import businessLogic.SessionsInTheRoom;
import businessLogic.WindowManager;
import entity.E_CITIES;
import entity.Studio;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.ButtonModel;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Shai Gutman
 */
public class AddQualification extends javax.swing.JPanel {
        
    public AddQualification() {
        if (WindowManager.getTmpFreelancer() == null) {
            return;
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        musicianPanel = new javax.swing.JPanel();
        addInstrumentLabel = new javax.swing.JLabel();
        clickLabel = new javax.swing.JLabel();
        cannotLabel = new javax.swing.JLabel();
        instrumentLabel = new javax.swing.JLabel();
        wageLabel = new javax.swing.JLabel();
        wageTextField = new javax.swing.JTextField();
        instrumentTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        instrumentComboBox = new javax.swing.JComboBox<>();
        soundmanPanel = new javax.swing.JPanel();
        mixCheckBox = new javax.swing.JCheckBox();
        masterCheckBox = new javax.swing.JCheckBox();
        producerCheckBox = new javax.swing.JCheckBox();
        mixLabel = new javax.swing.JLabel();
        advancedLabel = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();
        masterLabel = new javax.swing.JLabel();
        ProducerLabel = new javax.swing.JLabel();
        advancedTextField = new javax.swing.JTextField();
        totalTextField = new javax.swing.JTextField();
        saveButton0 = new javax.swing.JButton();
        musicianLabel = new javax.swing.JLabel();
        soundmanLabel = new javax.swing.JLabel();
        SoundmanRadioButton = new javax.swing.JRadioButton();
        MusicianRadioButton = new javax.swing.JRadioButton();
        roomCountLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        musicianPanel.setVisible(false);
        musicianPanel.setOpaque(false);
        musicianPanel.setLayout(null);

        addInstrumentLabel.setForeground(new java.awt.Color(0, 0, 0));
        addInstrumentLabel.setText("Add instrument:");
        addInstrumentLabel.setVisible(false);
        musicianPanel.add(addInstrumentLabel);
        addInstrumentLabel.setBounds(30, 150, 120, 30);

        Font font = clickLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        clickLabel.setFont(font.deriveFont(attributes));
        clickLabel.setForeground(new java.awt.Color(0, 0, 204));
        clickLabel.setText("click here");
        clickLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickLabelMouseClicked(evt);
            }
        });
        musicianPanel.add(clickLabel);
        clickLabel.setBounds(190, 110, 90, 30);

        cannotLabel.setForeground(new java.awt.Color(0, 0, 0));
        cannotLabel.setText("Cannot find an instrument?");
        musicianPanel.add(cannotLabel);
        cannotLabel.setBounds(30, 110, 170, 30);

        instrumentLabel.setForeground(new java.awt.Color(0, 0, 0));
        instrumentLabel.setText("Instrument:");
        musicianPanel.add(instrumentLabel);
        instrumentLabel.setBounds(30, 70, 120, 30);

        wageLabel.setForeground(new java.awt.Color(0, 0, 0));
        wageLabel.setText("Hourly wage:");
        musicianPanel.add(wageLabel);
        wageLabel.setBounds(30, 30, 110, 30);
        musicianPanel.add(wageTextField);
        wageTextField.setBounds(150, 30, 140, 30);

        instrumentTextField.setVisible(false);
        musicianPanel.add(instrumentTextField);
        instrumentTextField.setBounds(150, 150, 140, 30);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        musicianPanel.add(saveButton);
        saveButton.setBounds(270, 210, 100, 26);

        instrumentComboBox.addItem("Select Instrument");
        for (String s : AddQualificationControl.getAllInstruments())
        instrumentComboBox.addItem(s);
        musicianPanel.add(instrumentComboBox);
        instrumentComboBox.setBounds(150, 70, 140, 30);

        add(musicianPanel);
        musicianPanel.setBounds(70, 260, 410, 300);

        soundmanPanel.setVisible(false);
        soundmanPanel.setOpaque(false);
        soundmanPanel.setLayout(null);

        mixCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheckBoxActionPerformed(evt);
            }
        });
        soundmanPanel.add(mixCheckBox);
        mixCheckBox.setBounds(150, 190, 50, 30);

        masterCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterCheckBoxActionPerformed(evt);
            }
        });
        soundmanPanel.add(masterCheckBox);
        masterCheckBox.setBounds(150, 150, 50, 30);

        producerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producerCheckBoxActionPerformed(evt);
            }
        });
        soundmanPanel.add(producerCheckBox);
        producerCheckBox.setBounds(150, 110, 50, 30);

        mixLabel.setForeground(new java.awt.Color(0, 0, 0));
        mixLabel.setText("Mix technician:");
        soundmanPanel.add(mixLabel);
        mixLabel.setBounds(30, 190, 160, 30);

        advancedLabel.setForeground(new java.awt.Color(0, 0, 0));
        advancedLabel.setText("Advenced payment:");
        soundmanPanel.add(advancedLabel);
        advancedLabel.setBounds(30, 70, 120, 30);

        totalLabel1.setForeground(new java.awt.Color(0, 0, 0));
        totalLabel1.setText("Total payment:");
        soundmanPanel.add(totalLabel1);
        totalLabel1.setBounds(30, 30, 110, 30);

        masterLabel.setForeground(new java.awt.Color(0, 0, 0));
        masterLabel.setText("Master technician:");
        soundmanPanel.add(masterLabel);
        masterLabel.setBounds(30, 150, 160, 30);

        ProducerLabel.setForeground(new java.awt.Color(0, 0, 0));
        ProducerLabel.setText("Producer:");
        soundmanPanel.add(ProducerLabel);
        ProducerLabel.setBounds(30, 110, 110, 30);
        soundmanPanel.add(advancedTextField);
        advancedTextField.setBounds(150, 70, 140, 30);
        soundmanPanel.add(totalTextField);
        totalTextField.setBounds(150, 30, 140, 30);

        saveButton0.setText("Save");
        saveButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton0ActionPerformed(evt);
            }
        });
        soundmanPanel.add(saveButton0);
        saveButton0.setBounds(270, 250, 100, 26);

        add(soundmanPanel);
        soundmanPanel.setBounds(70, 260, 410, 300);

        musicianLabel.setVisible(false);
        musicianLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        musicianLabel.setForeground(new java.awt.Color(0, 0, 0));
        musicianLabel.setText("Musician");
        add(musicianLabel);
        musicianLabel.setBounds(280, 220, 140, 30);

        soundmanLabel.setVisible(false);
        soundmanLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        soundmanLabel.setForeground(new java.awt.Color(0, 0, 0));
        soundmanLabel.setText("Soundman");
        add(soundmanLabel);
        soundmanLabel.setBounds(500, 220, 120, 30);

        buttonGroup1.add(SoundmanRadioButton);
        SoundmanRadioButton.setContentAreaFilled(false);
        SoundmanRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SoundmanRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Soundman1.png"))); // NOI18N
        SoundmanRadioButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Soundman2.png"))); // NOI18N
        SoundmanRadioButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Soundman2.png"))); // NOI18N
        SoundmanRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SoundmanRadioButtonStateChanged(evt);
            }
        });
        add(SoundmanRadioButton);
        SoundmanRadioButton.setBounds(480, 80, 128, 128);

        buttonGroup1.add(MusicianRadioButton);
        MusicianRadioButton.setContentAreaFilled(false);
        MusicianRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MusicianRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Musician1.png"))); // NOI18N
        MusicianRadioButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Musician2.png"))); // NOI18N
        MusicianRadioButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Musician2.png"))); // NOI18N
        MusicianRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MusicianRadioButtonStateChanged(evt);
            }
        });
        add(MusicianRadioButton);
        MusicianRadioButton.setBounds(260, 80, 128, 128);

        roomCountLabel.setForeground(new java.awt.Color(0, 0, 0));
        add(roomCountLabel);
        roomCountLabel.setBounds(190, 160, 90, 20);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Add Qualification");
        add(titleLabel);
        titleLabel.setBounds(0, 10, 850, 40);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void SoundmanRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SoundmanRadioButtonStateChanged
        ButtonModel mod = SoundmanRadioButton.getModel();
        autoFillSoundman(AddQualificationControl.alreadySoundman(WindowManager.getTmpFreelancer().getFreelancerID()));
        if (SoundmanRadioButton.isSelected()) {
            soundmanLabel.setVisible(true);
            musicianLabel.setVisible(false);
            musicianPanel.setVisible(false);
            soundmanPanel.setVisible(true);
            return;
        }
        if (mod.isRollover()) {
            soundmanLabel.setVisible(true);
            return;
        }
        soundmanLabel.setVisible(false);
    }//GEN-LAST:event_SoundmanRadioButtonStateChanged

    private void MusicianRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MusicianRadioButtonStateChanged
        ButtonModel mod = MusicianRadioButton.getModel();
        autoFillMusician(AddQualificationControl.alreadyMusician(WindowManager.getTmpFreelancer().getFreelancerID()));
        if (MusicianRadioButton.isSelected()) {
            musicianLabel.setVisible(true);
            soundmanLabel.setVisible(false);
            soundmanPanel.setVisible(false);
            musicianPanel.setVisible(true);
            return;
        }
        if (mod.isRollover()) {
            musicianLabel.setVisible(true);
            return;
        }
        musicianLabel.setVisible(false);
    }//GEN-LAST:event_MusicianRadioButtonStateChanged

    private void producerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producerCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producerCheckBoxActionPerformed

    private void masterCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterCheckBoxActionPerformed

    private void mixCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixCheckBoxActionPerformed

    private void saveButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton0ActionPerformed
        String freelancerID = WindowManager.getTmpFreelancer().getFreelancerID();
        boolean master = masterCheckBox.isSelected();
        boolean mix = mixCheckBox.isSelected();
        boolean producer = producerCheckBox.isSelected();
        if (AddQualificationControl.insertNewSoundman(freelancerID, advancedTextField.getText(), totalTextField.getText(), producer, master, mix)) {
            WindowManager.openWin(new AddQualification());
            return;
        }
    }//GEN-LAST:event_saveButton0ActionPerformed

    private void clickLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickLabelMouseClicked
        if (!instrumentTextField.isVisible()) {
            instrumentTextField.setVisible(true);
            addInstrumentLabel.setVisible(true);
            return;
        }
        instrumentTextField.setText("");
        instrumentTextField.setVisible(false);
        addInstrumentLabel.setVisible(false);
    }//GEN-LAST:event_clickLabelMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String freelancerID = WindowManager.getTmpFreelancer().getFreelancerID();
        String instrument;
        boolean isNew = true;
        if (instrumentComboBox.getSelectedIndex() != 0 && instrumentTextField.getText().isEmpty()) {
            instrument = String.valueOf(instrumentComboBox.getSelectedItem());
            isNew = false;
        } else instrument = instrumentTextField.getText();
        if (AddQualificationControl.insertNewMusician(freelancerID, wageTextField.getText(), instrument, isNew)) {
            WindowManager.openWin(new AddQualification());
            return;
        }
    }//GEN-LAST:event_saveButtonActionPerformed

public void autoFillSoundman(SoundMan tmp) {
    if (tmp == null) 
        return;
    totalTextField.setText(String.valueOf(tmp.getTotalPayment()));
    totalTextField.setEditable(false);
    advancedTextField.setText(String.valueOf(tmp.getAdvancePay()));
    advancedTextField.setEditable(false);
    masterCheckBox.setSelected(tmp.isMasterTech());
    masterCheckBox.setEnabled(false);
    mixCheckBox.setSelected(tmp.isMixTech());
    mixCheckBox.setEnabled(false);
    producerCheckBox.setSelected(tmp.isProducer());
    producerCheckBox.setEnabled(false);
    saveButton0.setEnabled(false);
}

public void autoFillMusician(Musician tmp) {
    if (tmp == null) 
        return;
    wageTextField.setText(String.valueOf(tmp.getCommission()));
    wageTextField.setEditable(false);
    instrumentComboBox.setSelectedItem(tmp.getType());
    instrumentComboBox.setEnabled(false);
    cannotLabel.setVisible(false);
    clickLabel.setVisible(false);
    saveButton.setEnabled(false);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MusicianRadioButton;
    private javax.swing.JLabel ProducerLabel;
    private javax.swing.JRadioButton SoundmanRadioButton;
    private javax.swing.JLabel addInstrumentLabel;
    private javax.swing.JLabel advancedLabel;
    private javax.swing.JTextField advancedTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cannotLabel;
    private javax.swing.JLabel clickLabel;
    private javax.swing.JComboBox<String> instrumentComboBox;
    private javax.swing.JLabel instrumentLabel;
    private javax.swing.JTextField instrumentTextField;
    private javax.swing.JCheckBox masterCheckBox;
    private javax.swing.JLabel masterLabel;
    private javax.swing.JCheckBox mixCheckBox;
    private javax.swing.JLabel mixLabel;
    private javax.swing.JLabel musicianLabel;
    private javax.swing.JPanel musicianPanel;
    private javax.swing.JCheckBox producerCheckBox;
    private javax.swing.JLabel roomCountLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton0;
    private javax.swing.JLabel soundmanLabel;
    private javax.swing.JPanel soundmanPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JLabel wageLabel;
    private javax.swing.JTextField wageTextField;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
