/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import entity.Musician;
import businessLogic.CreateSessionControl;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import entity.Room;
import entity.SoundMan;
import businessLogic.SessionsInTheRoom;
import businessLogic.WindowManager;
import entity.E_CITIES;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Shai Gutman
 */
public class AddRoom extends javax.swing.JPanel {
        
    public AddRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recCheckBox = new javax.swing.JCheckBox();
        priceLabel = new javax.swing.JLabel();
        roomNumberLabel = new javax.swing.JLabel();
        roomField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        studioComboBox = new javax.swing.JComboBox<>();
        capacityField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        existedRoomsLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        studioNameLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);
        add(recCheckBox);
        recCheckBox.setBounds(190, 170, 30, 30);

        priceLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 0, 0));
        priceLabel.setText("Price per hour:");
        add(priceLabel);
        priceLabel.setBounds(60, 260, 130, 20);

        roomNumberLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        roomNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        roomNumberLabel.setText("Room number:");
        add(roomNumberLabel);
        roomNumberLabel.setBounds(60, 140, 130, 20);
        add(roomField);
        roomField.setBounds(190, 130, 180, 30);
        add(priceField);
        priceField.setBounds(190, 250, 180, 30);

        studioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(studioComboBox);
        studioComboBox.setBounds(190, 80, 180, 30);
        add(capacityField);
        capacityField.setBounds(190, 210, 180, 30);

        createButton.setText("Create Room");
        add(createButton);
        createButton.setBounds(520, 260, 140, 26);

        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(60, 390, 650, 170);

        existedRoomsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        existedRoomsLabel.setForeground(new java.awt.Color(0, 0, 0));
        existedRoomsLabel.setText("Existed rooms :");
        add(existedRoomsLabel);
        existedRoomsLabel.setBounds(60, 370, 130, 20);

        capacityLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        capacityLabel.setForeground(new java.awt.Color(0, 0, 0));
        capacityLabel.setText("Capacity:");
        add(capacityLabel);
        capacityLabel.setBounds(60, 220, 130, 20);

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("Recording cell:");
        add(emailLabel);
        emailLabel.setBounds(60, 180, 130, 20);

        studioNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studioNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        studioNameLabel.setText("Studio number:");
        add(studioNameLabel);
        studioNameLabel.setBounds(60, 90, 130, 20);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Add Room");
        add(titleLabel);
        titleLabel.setBounds(0, 10, 850, 40);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

public List<E_CITIES> ListOfCity(String country){
    List<E_CITIES> cityList = new ArrayList<E_CITIES>();

    for (E_CITIES city : E_CITIES.values()){
        if (country.equals(city.getCountry()) && !cityList.contains(city))
            cityList.add(city);
    }
    Collections.sort(cityList);
    return cityList;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacityField;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel existedRoomsLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JCheckBox recCheckBox;
    private javax.swing.JTextField roomField;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JComboBox<String> studioComboBox;
    private javax.swing.JLabel studioNameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
