/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.AddWorkWithStudioControl;
import entity.Musician;
import businessLogic.CreateSessionControl;
import businessLogic.CreateStudioControl;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import entity.Room;
import entity.SoundMan;
import businessLogic.SessionsInTheRoom;
import businessLogic.ValidatorManager;
import businessLogic.WindowManager;
import entity.E_CITIES;
import entity.Studio;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Shai Gutman
 */
public class AddWorkWithStudio extends javax.swing.JPanel {
        
    public AddWorkWithStudio() {
        if (WindowManager.getTmpFreelancer() == null) {
            return;
        }
        initComponents();
        switches = new ArrayList<>();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable() {
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 5:
                    return Boolean.class;
                    default:
                    return String.class;
                }
            }
        }
        ;
        housNumLabel1 = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        createButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(60, 80, 710, 250);

        housNumLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        housNumLabel1.setForeground(new java.awt.Color(0, 0, 0));
        housNumLabel1.setText("Please select the studios you wish to work with (press on the studio row to read about it):");
        add(housNumLabel1);
        housNumLabel1.setBounds(60, 60, 650, 20);

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionLabel.setText("Description:");
        add(descriptionLabel);
        descriptionLabel.setBounds(60, 340, 130, 20);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 360, 420, 120);

        createButton.setText("Update");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton);
        createButton.setBounds(570, 510, 140, 30);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Choose Studios");
        add(titleLabel);
        titleLabel.setBounds(0, 10, 850, 40);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        int counter = 0;
        for (Switched s:switches) {
            if (s.switchPos()) {
                if (AddWorkWithStudioControl.insertWork(s.Studio)) {
                    counter++;
                }
            } else if (AddWorkWithStudioControl.deleteWork(s.Studio)) {
                counter++;
            }
        }
        if (counter == switches.size()) {
            JOptionPane.showMessageDialog(null,
            "Working studios were updated!",
            "Updating complete",
            JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed

public void setTable(){
    DefaultTableModel model = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int col) {
                 switch (col) {
                     case 5:
                         return true;
                     default:
                         return false;
                  }
            }
    }; 
    jTable1.setModel(model);
    model.addColumn("No."); 
    model.addColumn("Name"); 
    model.addColumn("Email"); 
    model.addColumn("Phone"); 
    model.addColumn("Addrees");
    model.addColumn("Select");
    TableColumn tc = jTable1.getColumnModel().getColumn(5);
    tc.setCellEditor(jTable1.getDefaultEditor(Boolean.class));
    tc.setCellRenderer(jTable1.getDefaultRenderer(Boolean.class));
    model.setRowCount(0);
    boolean status;
    for (Studio s : CreateStudioControl.getStudios()) {
        status = AddWorkWithStudioControl.alreadyWork(s.getStudioID());
        model.addRow(new Object[]{s.getStudioID(),s.getStudioName(),s.getEmail(),s.getPhoneNum(), s.getAddress(), status});
        if (jTable1.getRowCount()>0) {
            switches.add(new Switched(s.getStudioID(), status, status, jTable1.getRowCount()-1));
        }
    }
    jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (jTable1.getSelectedRow() > -1) {
                String stdS = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                descriptionTextArea.setText(AddWorkWithStudioControl.getDescription(Integer.valueOf(stdS)));
                if (jTable1.getSelectedColumn() == 5) {
                    for (Switched switche : switches) {
                        if (switche.row == jTable1.getSelectedRow()) {
                            switche.setTo(!switche.from);
                        }
                    }
                }
            }    
        }
    });
}
class Switched {
    protected int Studio;
    protected boolean from;
    protected boolean to;
    protected int row;
    public Switched(int studio, boolean from,boolean to, int row){
        this.Studio = studio;
        this.from = from;
        this.to = to;
        this.row = row;
    }
    public void setTo(boolean to) {this.to = to;}
    public void setRow(int row) {this.row = row;}
    public boolean noSwitch() {return from == to;}
    public boolean switchPos() {return !from && to;}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel housNumLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
    ArrayList<Switched> switches;
}
