/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import entity.Musician;
import businessLogic.CreateSessionControll;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import entity.Room;
import entity.SoundMan;
import businessLogic.SessionsInTheRoom;
import businessLogic.WindowManager;
import entity.E_CITIES;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Shai Gutman
 */
public class CreateStudio extends javax.swing.JPanel {
        
    public CreateStudio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        housNumLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        studioNameField = new javax.swing.JTextField();
        studioNameLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        studioNameLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 210, 530, 140);

        descriptionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionLabel.setText("Description:");
        add(descriptionLabel);
        descriptionLabel.setBounds(60, 210, 130, 20);
        add(jTextField5);
        jTextField5.setBounds(540, 160, 150, 30);

        housNumLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        housNumLabel.setForeground(new java.awt.Color(0, 0, 0));
        housNumLabel.setText("House Number :");
        add(housNumLabel);
        housNumLabel.setBounds(430, 170, 100, 20);

        streetLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        streetLabel.setForeground(new java.awt.Color(0, 0, 0));
        streetLabel.setText("Street :");
        add(streetLabel);
        streetLabel.setBounds(430, 130, 110, 20);
        add(jTextField4);
        jTextField4.setBounds(540, 120, 150, 30);

        cityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(0, 0, 0));
        cityLabel.setText("City :");
        add(cityLabel);
        cityLabel.setBounds(430, 90, 90, 20);

        add(jComboBox2);
        jComboBox2.setBounds(540, 80, 150, 30);
        jComboBox2.removeAllItems();
        for (E_CITIES e : ListOfCity("Israel"))
        jComboBox2.addItem(e.toString());
        add(phoneField);
        phoneField.setBounds(160, 160, 150, 30);
        add(emailField);
        emailField.setBounds(160, 120, 150, 30);
        add(studioNameField);
        studioNameField.setBounds(160, 80, 150, 30);

        studioNameLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studioNameLabel1.setForeground(new java.awt.Color(0, 0, 0));
        studioNameLabel1.setText("Phone:");
        add(studioNameLabel1);
        studioNameLabel1.setBounds(60, 170, 130, 20);

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("Email:");
        add(emailLabel);
        emailLabel.setBounds(60, 130, 130, 20);

        studioNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studioNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        studioNameLabel.setText("Studio  name:");
        add(studioNameLabel);
        studioNameLabel.setBounds(60, 90, 130, 20);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Create New Studio");
        add(titleLabel);
        titleLabel.setBounds(60, 10, 230, 40);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

public List<E_CITIES> ListOfCity(String country){
    List<E_CITIES> cityList = new ArrayList<E_CITIES>();

    for (E_CITIES city : E_CITIES.values()){
        if (country.equals(city.getCountry()) && !cityList.contains(city))
            cityList.add(city);
    }
    Collections.sort(cityList);
    return cityList;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel housNumLabel;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField studioNameField;
    private javax.swing.JLabel studioNameLabel;
    private javax.swing.JLabel studioNameLabel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
