/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import entity.Musician;
import businessLogic.CreateSessionControl;
import businessLogic.CreateStudioControl;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import entity.Room;
import entity.SoundMan;
import businessLogic.SessionsInTheRoom;
import businessLogic.WindowManager;
import com.sun.org.apache.xerces.internal.impl.validation.ValidationManager;
import entity.E_CITIES;
import entity.Studio;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Shai Gutman
 */
public class CreateStudio extends javax.swing.JPanel {
        
    public CreateStudio() {
        initComponents();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        descriptionLabel = new javax.swing.JLabel();
        houseTextField = new javax.swing.JTextField();
        housNumLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        housNumLabel1 = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        studioNameField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        studioNameLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        studioNameLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(530, 80, 280, 140);

        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(60, 390, 650, 170);

        descriptionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionLabel.setText("Description:");
        add(descriptionLabel);
        descriptionLabel.setBounds(430, 90, 130, 20);
        add(houseTextField);
        houseTextField.setBounds(190, 320, 180, 30);

        housNumLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        housNumLabel.setForeground(new java.awt.Color(0, 0, 0));
        housNumLabel.setText("House Number :");
        add(housNumLabel);
        housNumLabel.setBounds(60, 330, 100, 20);

        streetLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        streetLabel.setForeground(new java.awt.Color(0, 0, 0));
        streetLabel.setText("Street :");
        add(streetLabel);
        streetLabel.setBounds(60, 290, 110, 20);
        add(streetTextField);
        streetTextField.setBounds(190, 280, 180, 30);

        cityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(0, 0, 0));
        cityLabel.setText("City :");
        add(cityLabel);
        cityLabel.setBounds(60, 250, 90, 20);

        housNumLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        housNumLabel1.setForeground(new java.awt.Color(0, 0, 0));
        housNumLabel1.setText("Existed studios :");
        add(housNumLabel1);
        housNumLabel1.setBounds(60, 370, 130, 20);

        cityComboBox.addItem("Select City");
        for (E_CITIES e : ListOfCity("Israel"))
        cityComboBox.addItem(e.toString());
        cityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBoxActionPerformed(evt);
            }
        });
        add(cityComboBox);
        cityComboBox.setBounds(190, 240, 180, 30);
        add(phoneField);
        phoneField.setBounds(190, 180, 180, 30);
        add(emailField);
        emailField.setBounds(190, 140, 180, 30);
        add(studioNameField);
        studioNameField.setBounds(190, 80, 180, 30);

        createButton.setText("Create Studio");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton);
        createButton.setBounds(530, 320, 140, 30);

        studioNameLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studioNameLabel1.setForeground(new java.awt.Color(0, 0, 0));
        studioNameLabel1.setText("Phone Number:");
        add(studioNameLabel1);
        studioNameLabel1.setBounds(60, 190, 130, 20);

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("Email:");
        add(emailLabel);
        emailLabel.setBounds(60, 150, 130, 20);

        studioNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studioNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        studioNameLabel.setText("Studio name:");
        add(studioNameLabel);
        studioNameLabel.setBounds(60, 90, 130, 20);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Create New Studio");
        add(titleLabel);
        titleLabel.setBounds(0, 10, 850, 40);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String studioName = studioNameField.getText();
        String description = descriptionTextArea.getText();
        String email = emailField.getText();
        String phone = phoneField.getText();
        String street  = streetTextField.getText();
        String house = houseTextField.getText();
        String city = String.valueOf(cityComboBox.getSelectedItem());
        if (CreateStudioControl.insertNewStudio(studioName, description, email, phone, street, house, city)) {
            WindowManager.openWin(new CreateStudio());
            return;
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void cityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityComboBoxActionPerformed

public List<E_CITIES> ListOfCity(String country){
    List<E_CITIES> cityList = new ArrayList<E_CITIES>();

    for (E_CITIES city : E_CITIES.values()){
        if (country.equals(city.getCountry()) && !cityList.contains(city))
            cityList.add(city);
    }
    Collections.sort(cityList);
    return cityList;
}

public void setTable(){
    DefaultTableModel model = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int col) {
                 switch (col) {
                     case 2:
                         return true;
                     default:
                         return false;
                  }
            }
    }; 
    jTable1.setModel(model);
    model.addColumn("No."); 
    model.addColumn("Name"); 
    model.addColumn("Addrees");
    model.setRowCount(0);
    for (Studio s : CreateStudioControl.getStudios()) {
        model.addRow(new Object[]{s.getStudioID(),s.getStudioName(), s.getAddress()});
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel housNumLabel;
    private javax.swing.JLabel housNumLabel1;
    private javax.swing.JTextField houseTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JTextField studioNameField;
    private javax.swing.JLabel studioNameLabel;
    private javax.swing.JLabel studioNameLabel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
