/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.SessionsInTheRoom;
import businessLogic.WindowManager;
import entity.SessionsRooms;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import org.hsqldb.SessionInterface;

/**
 *
 * @author Shai Gutman
 */
public class MainGui extends JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        setVisible(true);
        SessionsInTheRoom.setDebug(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genericButton3 = new javax.swing.JButton();
        arrowButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        genericButton2 = new javax.swing.JButton();
        genericButton1 = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1205, 725));
        setMinimumSize(new java.awt.Dimension(1205, 725));
        setPreferredSize(new java.awt.Dimension(1205, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        if (WindowManager.getAuthValue() == 2)
        genericButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/addRoomBtn.png"))); // NOI18N
        genericButton3.setBorderPainted(false);
        genericButton3.setContentAreaFilled(false);
        genericButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genericButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(genericButton3);
        genericButton3.setBounds(-20, 340, 216, 39);

        arrowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/arrowBtn.png"))); // NOI18N
        arrowButton.setBorder(null);
        arrowButton.setBorderPainted(false);
        arrowButton.setContentAreaFilled(false);
        arrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(arrowButton);
        arrowButton.setBounds(70, 610, 80, 65);

        if (WindowManager.getAuthValue() == 1)
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/artistBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 2)
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/repBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 3)
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/freelancerBtn.png"))); // NOI18N
        userButton.setBorder(null);
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        getContentPane().add(userButton);
        userButton.setBounds(1070, 520, 130, 40);

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logoutBtn.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(1070, 565, 130, 40);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exitBtn.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(1070, 610, 130, 40);

        if (WindowManager.getAuthValue() == 1)
        genericButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/viewSessionBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 2)
        genericButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/viewStudioBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 3)
        genericButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/addStudioBtn.png"))); // NOI18N
        genericButton2.setBorderPainted(false);
        genericButton2.setContentAreaFilled(false);
        genericButton2.setDisabledIcon(null);
        genericButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genericButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(genericButton2);
        genericButton2.setBounds(-20, 300, 216, 39);

        if (WindowManager.getAuthValue() == 1)
        genericButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/createSessionBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 2)
        genericButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/createStudioBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 3)
        genericButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/addQualificationBtn.png"))); // NOI18N
        genericButton1.setBorderPainted(false);
        genericButton1.setContentAreaFilled(false);
        genericButton1.setDisabledIcon(null);
        genericButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genericButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(genericButton1);
        genericButton1.setBounds(-20, 260, 216, 39);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/SessionBack.png"))); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genericButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genericButton1ActionPerformed
        setWindows(new CreateSession(), new CreateStudio(), null);
    }//GEN-LAST:event_genericButton1ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        WindowManager.openLogin();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonActionPerformed

    private void arrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowButtonActionPerformed
        WindowManager.returnWindow();
    }//GEN-LAST:event_arrowButtonActionPerformed

    private void genericButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genericButton2ActionPerformed
        
    }//GEN-LAST:event_genericButton2ActionPerformed

    private void genericButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genericButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genericButton3ActionPerformed

    private void setWindows(JPanel p1, JPanel p2, JPanel p3) {
        switch (WindowManager.getAuthValue()) {
            case 1:
                WindowManager.openWin(p1);
                break;
            case 2:
                WindowManager.openWin(p2);
                break;
            case 3:
                WindowManager.openWin(p3);
                break;
            default:
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrowButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton genericButton1;
    private javax.swing.JButton genericButton2;
    private javax.swing.JButton genericButton3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton userButton;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
